PROFILES = [
    {
        "id": "thorax-ct-demo",
        "displayName": "Thorax CT · TotalSeg-style",
        "summary": "Produces EXTERNAL, bilateral lungs, and heart draft candidates.",
        "modality": "CT",
        "anatomyScope": "Thorax",
        "expectedStructureLabels": ["EXTERNAL", "Lung_L", "Lung_R", "Heart"],
        "structures": [
            {"id": "lung_left", "name": "Lung_L", "type": "OAR", "color": [255, 140, 0], "totalsegLabel": "lung_left"},
            {"id": "lung_right", "name": "Lung_R", "type": "OAR", "color": [255, 165, 0], "totalsegLabel": "lung_right"},
            {"id": "heart", "name": "Heart", "type": "OAR", "color": [220, 20, 60], "totalsegLabel": "heart"},
            {"id": "external", "name": "EXTERNAL", "type": "EXTERNAL", "color": [255, 255, 0], "totalsegLabel": "body_trunc"},
        ],
    },
    {
        "id": "headneck-ct-demo",
        "displayName": "Head & Neck CT · TotalSeg-style",
        "summary": "Produces brain, brainstem, bilateral parotids, mandible, spinal cord.",
        "modality": "CT",
        "anatomyScope": "Head & Neck",
        "expectedStructureLabels": ["Brain", "BrainStem", "SpinalCord", "Parotid_L", "Parotid_R", "Mandible"],
        "structures": [
            {"id": "brain", "name": "Brain", "type": "OAR", "color": [255, 192, 203], "totalsegLabel": "brain"},
            {"id": "brainstem", "name": "BrainStem", "type": "OAR", "color": [148, 0, 211], "totalsegLabel": "brainstem"},
            {"id": "spinal_cord", "name": "SpinalCord", "type": "OAR", "color": [255, 255, 0], "totalsegLabel": "spinal_cord"},
            {"id": "parotid_left", "name": "Parotid_L", "type": "OAR", "color": [0, 255, 255], "totalsegLabel": "parotid_gland_left"},
            {"id": "parotid_right", "name": "Parotid_R", "type": "OAR", "color": [0, 200, 200], "totalsegLabel": "parotid_gland_right"},
            {"id": "mandible", "name": "Mandible", "type": "OAR", "color": [210, 180, 140], "totalsegLabel": "mandible"},
        ],
    },
    {
        "id": "abdomen-ct-demo",
        "displayName": "Upper Abdomen CT · TotalSeg-style",
        "summary": "Produces liver, spleen, kidneys, stomach, spinal cord.",
        "modality": "CT",
        "anatomyScope": "Abdomen",
        "expectedStructureLabels": ["Liver", "Spleen", "Kidney_L", "Kidney_R", "Stomach", "SpinalCord"],
        "structures": [
            {"id": "liver", "name": "Liver", "type": "OAR", "color": [165, 42, 42], "totalsegLabel": "liver"},
            {"id": "spleen", "name": "Spleen", "type": "OAR", "color": [128, 0, 128], "totalsegLabel": "spleen"},
            {"id": "kidney_left", "name": "Kidney_L", "type": "OAR", "color": [220, 20, 60], "totalsegLabel": "kidney_left"},
            {"id": "kidney_right", "name": "Kidney_R", "type": "OAR", "color": [200, 20, 40], "totalsegLabel": "kidney_right"},
            {"id": "stomach", "name": "Stomach", "type": "OAR", "color": [255, 215, 0], "totalsegLabel": "stomach"},
            {"id": "spinal_cord", "name": "SpinalCord", "type": "OAR", "color": [255, 255, 0], "totalsegLabel": "spinal_cord"},
        ],
    },
    {
        "id": "pelvis-ct-demo",
        "displayName": "Pelvis CT · TotalSeg-style",
        "summary": "Produces bladder, rectum, femoral heads, prostate, spinal cord.",
        "modality": "CT",
        "anatomyScope": "Pelvis",
        "expectedStructureLabels": ["Bladder", "Rectum", "FemoralHead_L", "FemoralHead_R", "CTV_Prostate", "SpinalCord"],
        "structures": [
            {"id": "bladder", "name": "Bladder", "type": "OAR", "color": [255, 215, 0], "totalsegLabel": "urinary_bladder"},
            {"id": "rectum", "name": "Rectum", "type": "OAR", "color": [165, 42, 42], "totalsegLabel": "rectum"},
            {"id": "femur_left", "name": "FemoralHead_L", "type": "OAR", "color": [210, 180, 140], "totalsegLabel": "femur_left"},
            {"id": "femur_right", "name": "FemoralHead_R", "type": "OAR", "color": [190, 160, 120], "totalsegLabel": "femur_right"},
            {"id": "prostate", "name": "CTV_Prostate", "type": "CTV", "color": [50, 205, 50], "totalsegLabel": "prostate"},
            {"id": "spinal_cord", "name": "SpinalCord", "type": "OAR", "color": [255, 255, 0], "totalsegLabel": "spinal_cord"},
        ],
    },
]
