_EXTERNAL = {
    "id": "external",
    "name": "External",
    "type": "EXTERNAL",
    "color": [255, 255, 255],
    "totalsegTask": "body",
    "totalsegLabels": ["body_trunc", "body_extremities"],
}

PROFILES = [
    {
        "id": "thorax-ct-demo",
        "displayName": "Thorax CT · TotalSegmentator",
        "summary": "Produces bilateral lungs and heart draft candidates.",
        "modality": "CT",
        "anatomyScope": "Thorax",
        "expectedStructureLabels": ["External", "Lung_L", "Lung_R", "Heart"],
        "structures": [
            _EXTERNAL,
            {
                "id": "lung_left",
                "name": "Lung_L",
                "type": "OAR",
                "color": [255, 140, 0],
                "totalsegTask": "total",
                "totalsegLabels": ["lung_upper_lobe_left", "lung_lower_lobe_left"],
            },
            {
                "id": "lung_right",
                "name": "Lung_R",
                "type": "OAR",
                "color": [255, 165, 0],
                "totalsegTask": "total",
                "totalsegLabels": ["lung_upper_lobe_right", "lung_middle_lobe_right", "lung_lower_lobe_right"],
            },
            {
                "id": "heart",
                "name": "Heart",
                "type": "OAR",
                "color": [220, 20, 60],
                "totalsegTask": "total",
                "totalsegLabels": ["heart"],
            },
        ],
    },
    {
        "id": "headneck-ct-demo",
        "displayName": "Head & Neck CT · TotalSegmentator",
        "summary": "Produces brain and spinal cord draft candidates (free 'total' task only).",
        "modality": "CT",
        "anatomyScope": "Head & Neck",
        "expectedStructureLabels": ["External", "Brain", "SpinalCord"],
        "structures": [
            _EXTERNAL,
            {
                "id": "brain",
                "name": "Brain",
                "type": "OAR",
                "color": [255, 192, 203],
                "totalsegTask": "total",
                "totalsegLabels": ["brain"],
            },
            {
                "id": "spinal_cord",
                "name": "SpinalCord",
                "type": "OAR",
                "color": [255, 255, 0],
                "totalsegTask": "total",
                "totalsegLabels": ["spinal_cord"],
            },
        ],
    },
    {
        "id": "abdomen-ct-demo",
        "displayName": "Upper Abdomen CT · TotalSegmentator",
        "summary": "Produces liver, spleen, kidneys, stomach, spinal cord.",
        "modality": "CT",
        "anatomyScope": "Abdomen",
        "expectedStructureLabels": ["External", "Liver", "Spleen", "Kidney_L", "Kidney_R", "Stomach", "SpinalCord"],
        "structures": [
            _EXTERNAL,
            {
                "id": "liver",
                "name": "Liver",
                "type": "OAR",
                "color": [165, 42, 42],
                "totalsegTask": "total",
                "totalsegLabels": ["liver"],
            },
            {
                "id": "spleen",
                "name": "Spleen",
                "type": "OAR",
                "color": [128, 0, 128],
                "totalsegTask": "total",
                "totalsegLabels": ["spleen"],
            },
            {
                "id": "kidney_left",
                "name": "Kidney_L",
                "type": "OAR",
                "color": [220, 20, 60],
                "totalsegTask": "total",
                "totalsegLabels": ["kidney_left"],
            },
            {
                "id": "kidney_right",
                "name": "Kidney_R",
                "type": "OAR",
                "color": [200, 20, 40],
                "totalsegTask": "total",
                "totalsegLabels": ["kidney_right"],
            },
            {
                "id": "stomach",
                "name": "Stomach",
                "type": "OAR",
                "color": [255, 215, 0],
                "totalsegTask": "total",
                "totalsegLabels": ["stomach"],
            },
            {
                "id": "spinal_cord",
                "name": "SpinalCord",
                "type": "OAR",
                "color": [255, 255, 0],
                "totalsegTask": "total",
                "totalsegLabels": ["spinal_cord"],
            },
        ],
    },
    {
        "id": "pelvis-ct-demo",
        "displayName": "Pelvis CT · TotalSegmentator",
        "summary": "Produces bladder, colon, femoral heads, prostate, spinal cord.",
        "modality": "CT",
        "anatomyScope": "Pelvis",
        "expectedStructureLabels": ["External", "Bladder", "Colon", "FemoralHead_L", "FemoralHead_R", "CTV_Prostate", "SpinalCord"],
        "structures": [
            _EXTERNAL,
            {
                "id": "bladder",
                "name": "Bladder",
                "type": "OAR",
                "color": [255, 215, 0],
                "totalsegTask": "total",
                "totalsegLabels": ["urinary_bladder"],
            },
            {
                "id": "colon",
                "name": "Colon",
                "type": "OAR",
                "color": [165, 42, 42],
                "totalsegTask": "total",
                "totalsegLabels": ["colon"],
            },
            {
                "id": "femur_left",
                "name": "FemoralHead_L",
                "type": "OAR",
                "color": [210, 180, 140],
                "totalsegTask": "total",
                "totalsegLabels": ["femur_left"],
            },
            {
                "id": "femur_right",
                "name": "FemoralHead_R",
                "type": "OAR",
                "color": [190, 160, 120],
                "totalsegTask": "total",
                "totalsegLabels": ["femur_right"],
            },
            {
                "id": "prostate",
                "name": "CTV_Prostate",
                "type": "CTV",
                "color": [50, 205, 50],
                "totalsegTask": "total",
                "totalsegLabels": ["prostate"],
            },
            {
                "id": "spinal_cord",
                "name": "SpinalCord",
                "type": "OAR",
                "color": [255, 255, 0],
                "totalsegTask": "total",
                "totalsegLabels": ["spinal_cord"],
            },
        ],
    },
]
